name: 'Terraform Apply'

on:
  push:
    branches:
      - develop
      - stage
      - prod

permissions:
  contents: read

jobs:  
  apply:
    name: 'Terraform Apply from ${{ github.ref_name }} branch'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Configire AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend-config=config/${{ github.ref_name }}.tfvars
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -var-file=config/${{ github.ref_name }}.tfvars
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      working-directory: ./terraform
